apiVersion: spec.paws.sh/v1alpha1
kind: Workload
metadata:
  name: products-catalog
spec:
  resources:
    db:
      type: postgres
    file-storage:
       type:S3
    api-dns:
      type: dns
  container:
    variables:
      CONNECTION_STRING: postgresql://${resources.db.user}:${resources.db.password}@${resources.db.host}:${resources.db.port}/${resources.db.name}
